export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAIL = "GET_SUBJECTS_FAIL";
export const GET_SUBJECTS_LOADING = "GET_SUBJECTS_LOADING";
//get my subjects actions types
// export const GET_MY_SUBJECTS_SUCCESS = "GET_MY_SUBJECTS_SUCCESS";
// export const GET_MY_SUBJECTS_FAIL = "GET_MY_SUBJECTS_FAIL";
// export const GET_MY_SUBJECTS_LOADING = "GET_MY_SUBJECTS_LOADING";
//delete SUBJECT actions Types
export const DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";

//add SUBJECT actions types
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
//details SUBJECT actions types
export const GET_ONE_SUBJECT_FAIL = "GET_ONE_SUBJECT_FAIL";
export const GET_ONE_SUBJECT_SUCCESS = "GET_ONE_SUBJECT_SUCCESS";
//update SUBJECT actions types
export const UPDATE_ONE_SUBJECT_FAIL = "UPDATE_ONE_SUBJECT_FAIL";
export const UPDATE_ONE_SUBJECT_SUCCESS = "UPDATE_ONE_SUBJECT_SUCCESS";
