//signup
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
//signin
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
//delete
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
//get current user:
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

//get all users
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAILL";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_USERS_LOADING = "GET_USERS_LOADING";


//logout:
export const LOGOUT = "LOGOUT";
//update user
export const UPDATE_ONE_USER_FAIL = "UPDATE_ONE_USER_FAIL";
export const UPDATE_ONE_USER_SUCCESS = "UPDATE_ONE_USER_SUCCESS";
export const UPDATE_PASSWORD_USER_FAIL = "UPDATE_PASSWORD_USER_FAIL";
export const UPDATE_PASSWORD_USER_SUCCESS = "UPDATE_PASSWORD_USER_SUCCESS";
